### ISSUE TITLE
Hide Cape

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [mrmelon54/armored-elytra-fabric#6]
The cape is not hidden when wearing an elytra with armor, so both the elytra and cape is shown.

**Comment by mrmelon54** [comment]
Are you talking about vanilla capes or capes added by a specific mod?

**Comment by MacaylaMarvelous81** [comment]
OptiFine capes

**Comment by mrmelon54** [comment]
Do you mean the mod OptiFine or the fabric mod called of-capes?

**Comment by MacaylaMarvelous81** [comment]
the mod optifine

**Comment by mrmelon54** [comment]
Due to Optifine being a forge mod and requiring optifabric for fabric support and Optifine being closed source and thus more difficult for me to override features (e.g. temporarily disabling the cape). As a result of this I am not going fix this issue.

I'm pretty sure this mod does work with of-capes and I'll be happy to fix any issue relating to that or other fabric mods.

**Comment by MacaylaMarvelous81** [comment]
Thanks
